config/routes.rb
Cute::Application.routes.draw do


  get "home/index"

  root :to => 'home#index'

  resources :photos
#  resources :blogs
  resources :users
  resources :likes
#  resources :password
  
  

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  
 get ':name', :controller => 'people', :action => 'show', :as => :person
#put passwords and profile to one directory  
  namespace :settings do
    resource :password, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authorize
  def index
    @user = current_user
    @photos = Photo.order_by([[:created_at, :desc]]).limit(20)
#    @photos_own = Photo.find_by(user_id:current_user.id).to_a
  end

#  protected

#  def find_own_photos
#    @photos_own = Photo.find(user_id:current_user)
#    
#  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/.#index.html.erb
jialezhang@jialezhang-Lenovo-G460.3880:1345084694

app/views/home/index.haml
.container-fluid
  .row-fluid.photos_show_border
    %ul.photo_show
      = render :partial => 'photos/photo'
  .row-fluid.span2
    - if logined?
      - if @photos_own.nil?
        %p
          = current_user.name
      - else
        - @photos_own.each do |photo_own|
          %p.photo_des
            = photo_own.description
          %p
            = image_tag photo_own.content.scan.url
 
              

app/views/home/index.html.erb
<% if session[:user_id] !=nil %>
<%= @user.name %>
<%= link_to "log out ", logout_path ,:method => "delete"%>
<div class="user_own_upload">
	<%= link_to 'user_own_upload', new_photo_path %>
</div>
<div id="settings">
	<%= link_to 'settings', settings_profile_path %>
</div>
<% end %>
<% @photos.each  do |photo| %>
<div class="photos">
	<p><%= image_tag photo.content.url %></p>
	<p><%= photo.description %></p>
</div>
<% end %>