config/routes.rb
Cute::Application.routes.draw do


  get "home/index"

  root :to => 'home#index'

  resources :photos
#  resources :blogs
  resources :users
  resources :likes
#  resources :password
  
  

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  
 get ':name', :controller => 'people', :action => 'show', :as => :person
#put passwords and profile to one directory  
  namespace :settings do
    resource :password, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end

end

app/models/.#photos.rb
jialezhang@jialezhang-Lenovo-G460.3880:1345084694

app/models/blog.rb
class Blog
  include Mongoid::Document
  field :name, type: String
  field :content, type: String
  field :tag, type: String
end

app/models/like.rb
class Like
  include Mongoid::Document
  field :photo_id, type: String
  field :likes_user_ids, type: Array, default: []
  # field :likes_count, type: Integer, default: 0

  # belongs_to :user
  belongs_to :photo
 
  def liked_by_user?(user)
    return false if user.blank?
    self.likes_user_ids.include?(user.id)
    
  end
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  
  field :name, type: String
 # field :tag, type: Array
  field :content, type: String
  field :description, type: String
  field :actived_at, type: Time
  field :liker_ids, type: Array, default: []
  # field :replies_

  belongs_to :user
#  has_many   :replies, :dependent => :delete
  
  validates :content, :name, :user, :presence => true

  mount_uploader :content, UpphotosUploader

  before_create :set_actived_at

   def set_actived_at
    self.actived_at = Time.now.utc
   end

   def update_like_status_by(like)
     self.actived_at = like.create_at
     save
   end

   def reset_like_status
     last_like = likes.order([:create_at]).last
     if last_like
       update_like_status_by(last_like)
     else
       self.actived_at = created_at
       save
     end
   end

   def like_by(user)
     unless liked_by?(user) || self.user == user
       collection.update(
                  {:_id => self.id},
                  {"$AddToSet" => {:liker_ids => user.id}}
                  )
     end
   end
   def liked_by?(user)
     liker_ids.include?user.id
   end
end

app/models/profile.rb
class Profile
  include Mongoid::Document
  field :name, type: String
  field :url, type: String
  field :description, type: String
  embedded_in :user
  
  validates :name, :length => {:in => 3..20, :allow_blank => true}
  validates :url, :length => {:maximum => 100}
  validates :description, :length => {:maximum => 300}
  
  attr_accessible :name, :url, :description
end

app/models/reply.rb
class Reply
  include Mongoid::Document
  include Mongoid::Timestamps

  filed :content
  filed :mentioned_user_ids, :type => Array, :default => []

  belongs_to :user
  belongs_to :photo

  validates :content, :user, :photo, :presence => true
  after_create :update_photo
  after_destroy :reset_photo

  attr_accessible :content

  def update_photo
    photo.update_reply_stats_by(self)
    photo.reply_by user
  end
  def reset_photo
    photo.reset_reply_stats
    photo.
  end
end

app/models/user.rb
  require 'bcrypt'
  require 'digest/sha2'
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  include Mongoid::Timestamps
  include BCrypt

#  has_secure_password
  
  field :name, type:String
  field :email, type:String
  field :hashed_password, type:String
  field :salt, type:String 
  field :avatar, type:String
  
  #field :access_token
  #field :locale, :default => I18n.locale.to_s
  
  has_many :photos
  embeds_one :profile
  
  validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
  validates :name, :format => {:with => /\A\w+\z/, :message => 'only A-Z, a-z, _ allowed'}, :length => {:in => 3..20}
 # validates :email, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/}
  validates :password, :password_confirmation, :presence => true, :on => :create
  validates :password, :length => {:minimum => 6, :allow_nil => true}
  validates_presence_of :avatar
  #  validates :current_password, :current_password => {:fields => [:name, :email, :password]}, :on => :update
  attr_reader :password
  attr_accessor :current_password, :password_confirmation
  attr_accessible :name, :password, :password_confirmation, :current_password, :avatar
  
  mount_uploader :avatar, UploadAvatarUploader
  
  before_create :build_profile


  def User.encrypt_password(password,salt)
    Digest::SHA2.hexdigest(password+"wibble"+salt)
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password,salt)
    end
  end
  
  def User.authenticate(name,password)
    if user = User.find_by(name:name)
      if user.hashed_password == encrypt_password(password,user.salt)
        user
    end
    end
  end

  
  private
  def password_must_be_present
    errors.add(:password, "Missing password") unless hashed_password.present?
  end
  
end

 

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
#conding: utf-8
module LikesHelper
  def like_tag(photol, opts ={})
    return "" if photol.blank?

    if current_user && photol.liked_by?(current_user)
      status = "liked"
      icon = content_tag("div", "", :class => status)
    else
      status = "like"
      icon = content_tag("div", "", :class => status)
    end

     body = raw "#{icon}"
    # url = "#"
    # html = {:class => "photol", :rel => "twipsy",:onclick => "return App.like(this); ",
    #   'data-id' => photol.id,'data-status' => status}
    # link_to body,url,html
    link_to body, "#", :onclick => "return App.like(this);", 'data-status' => status, :class => "photol", 'data-id' => photol.id
   
  end
end
  

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/photoes_helper.rb
module PhotoesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/.#application.html.erb
jialezhang@jialezhang-Lenovo-G460.3880:1345084694

app/views/layouts/_footer.haml
%footer
  #container.btn
    click_to_top

app/views/layouts/_topbar.haml
.navbar
  .navbar-inner
    .container
      %ul
        %li.brand
          %a{:href => '/'}CuteAnimal
        %li.span4
          %a{:href => "/"}Home
        %li.span4
          %a{:href => "/"}Wait
      %ul.pull-right
        - if logined?
          %li.dropdown
            %a{:href => person_path(:name => current_user),
               :class => "dropdown-toggle",
               'data-toggle' => 'dropdown', 'data-target' => '#'}
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'profiles', settings_profile_path
              %li
                = link_to 'password', settings_password_path
              %li.divider
              %li
                = link_to 'logout', logout_path, :method => :delete
        - else
          %li
            = link_to 'login', login_path
          %li
            = link_to 'signup', signup_path

app/views/layouts/application.haml
!!! 5
%html
  %head
    %meta{charset: "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title CuteAnimal
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render :partial => 'layouts/topbar'
    = yield
    = render :partial => 'layouts/footer'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cute</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>